let
    Origen = PostgreSQL.Database("cluster-guajiranet-instance-1.cur2img2cxzx.us-east-1.rds.amazonaws.com:5432", "db_bronze"),
    Navigation = Origen{[Schema="gold_guajiranet",Item="vw_anl_ciclo_vida_cliente_resumen"]}[Data],
    #"Columnas seleccionadas" = Table.SelectColumns(Navigation,{
        "sk_cliente",
        "nit",
        "idsuc",
        "fecha_inicio_transaccional_observada",
        "ultima_fecha_factura",
        "ultimo_mes_con_facturacion",
        "ultima_actividad_pago",
        "ultima_actividad_pago_aplicado",
        "ultima_actividad_pago_pasarela",
        "as_of_fecha",
        "dias_desde_ultima_factura",
        "meses_desde_ultima_factura",
        "activo_transaccional_actual",
        "cantidad_episodios_inactividad",
        "cantidad_recuperaciones_transaccionales",
        "cantidad_deserciones_observadas",
        "dias_totales_inactivo",
        "promedio_dias_inactivo",
        "max_dias_inactivo",
        "meses_totales_inactivo",
        "cantidad_episodios_interrupcion_pago",
        "cantidad_recuperaciones_pago",
        "cantidad_interrupciones_pago_abiertas",
        "dias_totales_sin_pago",
        "max_dias_sin_pago",
        "retiro_registrado",
        "fecha_retiro_registrada",
        "estado_retiro_registrado",
        "estado_activo_sucursal",
        "idperfilcartera",
        "cantidad_contratos_actuales",
        "cantidad_contratos_enabled",
        "plan_actual",
        "frequency_in_months",
        "actividad_facturacion_posterior_a_retiro",
        "pago_posterior_a_ultima_factura"
    }),
    #"Tipo cambiado" = Table.TransformColumnTypes(#"Columnas seleccionadas",{
        {"sk_cliente", Int64.Type},
        {"nit", Int64.Type},
        {"idsuc", Int64.Type},
        {"fecha_inicio_transaccional_observada", type date},
        {"ultima_fecha_factura", type date},
        {"ultimo_mes_con_facturacion", type date},
        {"ultima_actividad_pago", type date},
        {"ultima_actividad_pago_aplicado", type date},
        {"ultima_actividad_pago_pasarela", type date},
        {"as_of_fecha", type date},
        {"dias_desde_ultima_factura", Int64.Type},
        {"meses_desde_ultima_factura", Int64.Type},
        {"activo_transaccional_actual", type logical},
        {"cantidad_episodios_inactividad", Int64.Type},
        {"cantidad_recuperaciones_transaccionales", Int64.Type},
        {"cantidad_deserciones_observadas", Int64.Type},
        {"dias_totales_inactivo", Int64.Type},
        {"promedio_dias_inactivo", type number},
        {"max_dias_inactivo", Int64.Type},
        {"meses_totales_inactivo", type number},
        {"cantidad_episodios_interrupcion_pago", Int64.Type},
        {"cantidad_recuperaciones_pago", Int64.Type},
        {"cantidad_interrupciones_pago_abiertas", Int64.Type},
        {"dias_totales_sin_pago", Int64.Type},
        {"max_dias_sin_pago", Int64.Type},
        {"retiro_registrado", type logical},
        {"fecha_retiro_registrada", type date},
        {"estado_retiro_registrado", type text},
        {"estado_activo_sucursal", type text},
        {"idperfilcartera", Int64.Type},
        {"cantidad_contratos_actuales", Int64.Type},
        {"cantidad_contratos_enabled", Int64.Type},
        {"plan_actual", type text},
        {"frequency_in_months", Int64.Type},
        {"actividad_facturacion_posterior_a_retiro", type logical},
        {"pago_posterior_a_ultima_factura", type logical}
    }),
    #"sk_cliente texto" = Table.TransformColumns(#"Tipo cambiado",{
        {"sk_cliente", each if _ = null then null else Text.From(_), type text}
    })
in
    #"sk_cliente texto"
