let
    Origen = PostgreSQL.Database("cluster-guajiranet-instance-1.cur2img2cxzx.us-east-1.rds.amazonaws.com:5432", "db_bronze"),
    Navigation = Origen{[Schema="gold_guajiranet",Item="vw_anl_estado_transaccional_mensual_cliente"]}[Data],
    #"Columnas seleccionadas" = Table.SelectColumns(Navigation,{
        "sk_cliente",
        "nit",
        "idsuc",
        "mes",
        "primer_mes_actividad",
        "ultimo_mes_actividad_conocido",
        "facturas_mes",
        "ingresos_mes",
        "cantidad_pagos_aplicados",
        "valor_pago_aplicado",
        "cantidad_pagos_pasarela",
        "valor_pago_pasarela",
        "tiene_facturacion",
        "tiene_pago",
        "tiene_pago_aplicado",
        "tiene_pago_pasarela",
        "tiene_actividad_digital",
        "tiene_actividad",
        "meses_consecutivos_sin_facturacion",
        "meses_consecutivos_sin_pago",
        "estado_transaccional",
        "estado_pago",
        "pago_sin_facturacion_cercana",
        "pago_posterior_a_ultima_factura",
        "mes_con_retiro_registrado"
    }),
    #"Tipo cambiado" = Table.TransformColumnTypes(#"Columnas seleccionadas",{
        {"sk_cliente", Int64.Type},
        {"nit", Int64.Type},
        {"idsuc", Int64.Type},
        {"mes", type date},
        {"primer_mes_actividad", type date},
        {"ultimo_mes_actividad_conocido", type date},
        {"facturas_mes", Int64.Type},
        {"ingresos_mes", type number},
        {"cantidad_pagos_aplicados", Int64.Type},
        {"valor_pago_aplicado", type number},
        {"cantidad_pagos_pasarela", Int64.Type},
        {"valor_pago_pasarela", type number},
        {"tiene_facturacion", type logical},
        {"tiene_pago", type logical},
        {"tiene_pago_aplicado", type logical},
        {"tiene_pago_pasarela", type logical},
        {"tiene_actividad_digital", type logical},
        {"tiene_actividad", type logical},
        {"meses_consecutivos_sin_facturacion", Int64.Type},
        {"meses_consecutivos_sin_pago", Int64.Type},
        {"estado_transaccional", type text},
        {"estado_pago", type text},
        {"pago_sin_facturacion_cercana", type logical},
        {"pago_posterior_a_ultima_factura", type logical},
        {"mes_con_retiro_registrado", type logical}
    }),
    #"sk_cliente texto" = Table.TransformColumns(#"Tipo cambiado",{
        {"sk_cliente", each if _ = null then null else Text.From(_), type text}
    })
in
    #"sk_cliente texto"
