let
    Origen = PostgreSQL.Database("cluster-guajiranet-instance-1.cur2img2cxzx.us-east-1.rds.amazonaws.com:5432", "db_bronze"),
    Navigation = Origen{[Schema="gold_guajiranet",Item="vw_anl_episodios_ciclo_vida_cliente"]}[Data],
    #"Columnas seleccionadas" = Table.SelectColumns(Navigation,{
        "sk_cliente",
        "nit",
        "idsuc",
        "numero_episodio",
        "tipo_episodio",
        "fecha_ultima_factura_previa",
        "fecha_inicio_inactividad",
        "fecha_primera_actividad_posterior",
        "fecha_fin_inactividad",
        "dias_inactivo",
        "meses_inactivo",
        "reconecto",
        "recuperacion_transaccional_observada",
        "meses_hasta_reconexion",
        "actividad_previa",
        "actividad_posterior",
        "facturacion_previa",
        "facturacion_posterior",
        "pagos_previos",
        "pagos_posteriores",
        "pagos_durante_inactividad",
        "hay_pago_durante_inactividad",
        "fecha_retiro_registrada",
        "estado_retiro_registrado",
        "motivo_inferido",
        "nivel_confianza"
    }),
    #"Tipo cambiado" = Table.TransformColumnTypes(#"Columnas seleccionadas",{
        {"sk_cliente", Int64.Type},
        {"nit", Int64.Type},
        {"idsuc", Int64.Type},
        {"numero_episodio", Int64.Type},
        {"tipo_episodio", type text},
        {"fecha_ultima_factura_previa", type date},
        {"fecha_inicio_inactividad", type date},
        {"fecha_primera_actividad_posterior", type date},
        {"fecha_fin_inactividad", type date},
        {"dias_inactivo", Int64.Type},
        {"meses_inactivo", type number},
        {"reconecto", type logical},
        {"recuperacion_transaccional_observada", type logical},
        {"meses_hasta_reconexion", type number},
        {"actividad_previa", type text},
        {"actividad_posterior", type text},
        {"facturacion_previa", Int64.Type},
        {"facturacion_posterior", Int64.Type},
        {"pagos_previos", Int64.Type},
        {"pagos_posteriores", Int64.Type},
        {"pagos_durante_inactividad", Int64.Type},
        {"hay_pago_durante_inactividad", type logical},
        {"fecha_retiro_registrada", type date},
        {"estado_retiro_registrado", type text},
        {"motivo_inferido", type text},
        {"nivel_confianza", type text}
    }),
    #"sk_cliente texto" = Table.TransformColumns(#"Tipo cambiado",{
        {"sk_cliente", each if _ = null then null else Text.From(_), type text}
    })
in
    #"sk_cliente texto"
